idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "web_server.c"
        "uart_motor.c"
        "imu_sensor.c"
        "ros_serial.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_http_server
        spiffs
        mdns
        driver
        esp_timer
        cjson
)
